import {Component, ViewChild} from '@angular/core';
import {Camera, CameraOptions} from '@ionic-native/camera';
import {AlertController, NavController, NavParams, Platform} from "ionic-angular";
import {Gift} from "../../app/domain/gift";
import {GiftStore} from "../../providers/giftstore";
import {AuthServiceProvider} from "../../providers/auth-service/auth-service";
import {NoticeController} from "../../providers/view/notice/NoticeController";


@Component({
             selector: 'page-gift',
             templateUrl: 'gift.html',
           })
export class GiftPage {
  @ViewChild('title') title: any;

  public base64Image: string[] = [];

  gift: Gift = new Gift("");
  giftOriginal: Gift = new Gift("");
  public changing: boolean = false;

  constructor(private camera: Camera,
              private _nav: NavController,
              private _navParams: NavParams,
              private _giftStore: GiftStore,
              private _auth: AuthServiceProvider,
              private _alertCtrl: AlertController,
              private _noticeCtrl: NoticeController,
              private _platform: Platform) {
  }

  ionViewDidLoad() {
    if (this._navParams.data.hasOwnProperty("gift")) {
      this.gift = this._navParams.get("gift") as Gift;
      this.changing = true;

    }
    this.giftOriginal = {...this.gift};

    this.gift.owner = this._auth.uid;
  }

  ngOnInit() {
    setTimeout(() => {
      this.title.setFocus();
    }, 150);
  }

  ionViewCanLeave(): boolean | Promise<void> {
    let same = (key: string) => {
      let g1: any = (<any> this.gift)[key];
      let g2: any = (<any> this.giftOriginal)[key];

      console.debug("key:" + key, g1, g2);
      return g1 === g2
    };

    let hasChanged = () => {
      return !['title', 'estimatedPrice', 'description'].every(key => same(key));
    };

    return new Promise<void>((ok, cancel) => {
      if (hasChanged()) {
        let options = {
          title: 'Abbrechen',
          message: 'Du verlierst deine Änderungen, weiter?',
          buttons: [
            {
              text: 'Abbrechen',
              role: 'cancel',
              handler: () => cancel()
            },
            {
              text: 'Ok',
              handler: () => ok()
            }
          ]
        };
        this._alertCtrl.create(options).present();
      } else {
        ok();
      }
    });
  }

  tooglePictures() {
    if (this.base64Image.length) {
      let opts = {
        title: 'Bilder entfernen',
        message: 'Möchtest du alle Bilder entfernen?',
        buttons: [
          {
            text: 'Abbrechen',
            role: 'cancel',
            handler: () => {
              console.log('Cancel clicked');
            }
          },
          {
            text: 'Entfernen',
            handler: () => {
              this.base64Image = [];
            }
          }
        ]
      };
      this._alertCtrl.create(opts).present();
    } else {
      this.takeAnotherPicture();
    }
  }

  private takeAnotherPicture() {
    if (this._platform.is("core") || this._platform.is("mobileweb")) {
      this.base64Image.push(
        "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wgARCAPoA+gDASIAAhEBAxEB/8QAGwABAAIDAQEAAAAAAAAAAAAAAAYHAwQFAQL/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAGZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMPybAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGHNrlWYmEs3s1DZx0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR2vLkhxC+hzxa3Qp6eEleegAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz0Q2H3FxysW/oEnm9Q75a7k9YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1oLYfhTSeQY+p7XouX2GTI9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5XVFS6dt12ciRxwXBmq6xDdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxZRX0auWHELz4vksju01IixGjvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEfgduYCoEtip7MIWLhy1ROTvPPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzekK04lyx0rxuaZIJxU+QuJD5cfQAAAAAAAAAAAAAAAAAAAAAABwzHFOTiLP68BnwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhh03FOfFqV6c3tcUW3t1FPSQPPQAAAAAAAAAAAAAAAAAAAB4hpsQb5DKsg++sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4+xBYpcnFK092tQk03qLdLZcPtnoAAAAAAAAAAAAAAAAAGLDWxJISDa+rMMXTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADXhM+8KaWHBjVlcUFw5ansU6YAAAAAAAAAAAAAADyPncjcP0je0QdWRS45/RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABr7ArjgXLGiv/v3GWHI6bnZKXnoAAAAAAAAAAAMRl58YiZ3OABuzghExkv0eegAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxq5t/nFVOhzyRTepspcKHy0+wAAAAAAAAHxGDrwHn4gd44sslG8YcwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYIZOhTfzacEOP1+QLX36fnpI3noAAAAANU2eRGYwdTlAy9CdnHlvoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfH2IVEbj45WLd0iVTan+mWm53RAAAHxqQQ7kNwA9k5HprINo+PsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANaA2P8FOJ1BzLYda/RciKSo9MJljXCjhlxPs+Ot2Zoczq+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxO2KexWnXJpS2JC2a+5HgJKciw+hlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8H3xOXDTH4AHRtOm5GWGw5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8jp1YJyMIOucqZd/pnJr+1tcqFIo6dKxaozFwI5Ij0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5169OvDgfWxYBxJp9gADyHTIU58WdXZqymLC3tiopqSh56AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw94nPgxs6gOx15oa24AAAADU2xXscuTjFZulzSRzqot8tdyesAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUMsC0eUDomnPen0Tz0AAAAAAAMMInvhTSwIIeTyvxcvsBnBmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOaZa2w6oJaa88yegAAAAAAAAADmdMVNpW5ATg9XlC0OtTfZLLc/oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5HTZrn4+A+p8asvegAAAAAAAAAAAD4+xEoZcGoVIlkUM9i1llLhR2RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD41a7O1EfAy5rDMPeAAAAAAAAAAAAAAADyPSIU9is2tz4n1fi5fYhLT6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMRk4HDipnwPo+e115kYNoAAAAAAAAAAAAAAAAAHM6YqPVtWujnyGPC29uoJ+SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5GTqQHn4gd45lg9DaAAAAAAAAAAAAAAAAAAAAGHMIDGbk4hWmViLN7NPWGd4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxEhBwZduwDjy30AAAAAAAAAAAAAAAAAAAAAAAcat7h4xWX1kwk/k1NTYmDz0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYdWvjejgNzLZR87oAAAAAAAAAAAAAAAAAAAAAAAAAc2tbc0ipnQ55K5xTndLJau0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAONs1gMD08kXSmJhzgAAAAAAAAAAAAAAAAAAAAAAAAAABr17ZXwU4lUVNuwqy+i5EKmZ9AAAAAAAAAAAAAAAAAAAAAAAAAAAeexcjnED6sflTI89AAAAAAAAAAAAAAAAAAAAAAAAAAAAADzgSAU/htmujlyKOi4/ut52boAAAAAAAAAAAAAAAAAAAAAAAAAMNST6vB0OfZB2coAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPj7Fdx244SRLL8fJNpfTUrJ2+PsAAAAAAAAAAAAAAAAAAAAAAAAgEYk0ZNu2K1s0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5kBtHUKkdrinasKo+wWc0d4AAAAAAAAAAAAAAAAAAAAAAAgUWtyMHHsnn9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+IPO/CmkuiRlsas/ouRzuiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeR2RioPLa+TDvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//EACgQAAMAAgICAgIDAQADAQAAAAIDBAEFABAxYBFQEkATFDAgNDWwwP/aAAgBAQABBQL/AOK2bVr4D1M97af8aqKDpapppOC8aw95eH8iWqJLOIeU7Y6hrT7zs9f/AGRzj4zyOw5GzWJpx7zt9fj46U0knHuFu559488v0/zkwJZdQ7fKBU5bw94u14WDVGyQ+pbGSHFsF2Y94ehdAW6g0Y6Ww1Hr9oLx9488t04GJCQFzxzX7fnn3muBVQ0SsmPrX7QkEtgND3iicKVXa84y6i2DI8z1LpD3gwFg7DVGkulOYg4toqgfePPNhqMfBDkc88cj27UcnrTUPvF+sGrj5mzl0DDWUe6+eAYsH3dqVuGvSljJCQF1NY6bMe1TT7zVCmoa9W6bPce2ajk9aah+y2Ox/qYxt6/yguGxfoXnlmoU/lErZj6BhrKLc/lnGcZx9fdslyi1pOPmixn+z6IxQNCzS5xwhIC6j2bZcz0rpX9bsdt/DkiyZcUonHr48Rp9GqhTUNcLZWdIoZOcG0Cr6zYbfnnpSiccEAyB6QQiY7HU/hzOM4zzGc4zFtzTxD10B9OZisbdyH49TznS2SJcgel2axVWKJmTM6mrbKcm0TTj6WigJlV2srPqWcqXTSKlD01qFuGzTGvnjrxzX7bK+AwGD9CbAWNG7UHKrG1n1PrqKMxxhIr1C3Uro4+Zs5dTVtlKS5VS/wB+zbKRyit1RdeeazV4HHj1NqVvC3VNnz0JEBa3ZYoH9yi1Mw17Z1H/AAmJ78w6jCC9W2GqBwmBLLglkC1+2w79ozFY2brOeERGXU8jqij1KkcxjGPWb4BrBqWIPnjke3ajk9SqQ/WqvTJi3YMsz0CzYUel+cLUCg9brjXWuuNkjOltNRx7rGeCQmP6RFgcWbkF8a0nH1Fqm08nkTKPrzUrcNmlIOEORz1FsGSFNWqof0K9imXFWwdVnpazacWmwGfHsVUCasV610vammk4tsuj/Z9C5ws3Js5nOc56l17qsx69UePZCHBjZpfjhCQFzxyLcEvi2A0P8SLA4s3QhxrmOLpSGOKPTAvgjgcez269dY0yNlPqS9smZLF1r/7orTKN2zZV3jGc5j0xs4idc4e1PQugL9YUvanMQcOyXUP/ADftQThjTafUmudVmXXImx7aQ4LFunE8EOQLglkC122/mz0xgKDYbQnl0IkZR6XOeCOAH3C7XLqBqiSfPHItzkMZrRhV95Vn1NI2opIFSj7nXEusKZGyn185+OtfqjcQLBY+67Nk4z5+PnuEEnSPx+PuhFgcW7nA8Y02n18dxbc0YU0XB7lRWmUbtmyrsRyWdfqMfFOuRSFcbJGdSWskOatVQ+4W7Zc/GtNx9R651WZYEy46albwv1ZT56U00nFtl0e3ZzjGNht8/PnoRyZR6XOeCOAH/jzy/T/OSEgLnjke5JfFPW4fan0LnC7YsqPqec6Wxaxcv+NuvXWNE5zN6RQyc49yDOefaLdmqXlFLKWdQa86znlVMH+T5lUDZp2J5nGcZ6i25owh66A9l2O2/iyRZMueea7U5zkRwOP9a9YmrlUDpM9S2MkOLYLsx7ExgKDYbQnl0pROOLUAjP6DVC4LNMS+eOgMllr9qDh9gooCZVuwZZnqONlbJYkyj+ndqRfxqiSfUG2ynC2A0PXaKlzBZYdbetfqjcQLBY/q1xLrCmRsp9R7BseZdgmrHrdli5F0UHS3rWaz8+eP2KJ10rv1Zy9iWRzNtaEFLYusPWL9gEi2tNx88812px+Pj9ohwWLNKJ8aliS6Q9k5wXjWHq2y2WJxIiMuCOTLX6oEj+6+ZVA16XKxzjOM8Ww1HrdlinHqZFgcbHbZznOc5zxSiccOsXL9DsNYNOGqJJ8EsgWv2oOH1GipcwV7B1RdTzMpZDrwjH6K+AawaoknzxzWbTBYxnGcenW7VU+GuY8+odcyo0TrnD6SuJdYUTnM3rX7MpsopVQPpZmKx2O2/lx0I5LOv1GfkRwOPprIwrVVE6UulOYg9dsf7ePSar0yYt2DLM9TytpOHXLlD6lqhcFmmYvJDkc8U0knBeNYej3bfCCa0nH1Fqm08nnXMv6y7XLqBqiSfFNJJw7NdXo2z2f4c89LWbTi02Az4+vvgGsGqJJ8EsgWv2wu9E2e0/DnnqSNlbI9eqPH2N8A1g1RpPnjmu22Px8+gMYCg2G0J5dTyspOWcZk/Z2RrrXROczetbtf4uCWDH72qxcgW7Blmeo42VsnnCZX2tEq6QsjORvUOzZLyehdK/u77xkBrmPPqLUso4pQJD7dqVvC7WslLqepsxwbAKw+5sqGRLmk9vMYznOv1GPjx90Q4Mdjqf4sdCWRzr9vn5xnGcfbeObSvNNHBHJlr9eudX3tuqVRhqjSfWt2WZyEsGP2u2vwtfWlj+PQKJVUhXA2UuoNocvJ6lUh9m08LU08sbyKXNVABhYegEImOy1uZy6W01HFufzLz9lum/hJ1qpRRN6EQ4MbdMQ8IcjnrW7X+Lglgx+w3uc/2uSpy+gB/APRKoE1YuhKI+otm2Xk9AUq+v3v/l81P/sPRqJwpVbrGy96+8o2IsRT9fvQL+xzTgRXejkODHZar+LtTSSyPZJq+uonXSvOgx+Usa5A9I882eryOc4zjPBLIFC7L5PedjrMU4aliSUo3HIj+vN70als4CFL/wDwk/8A/8QAFBEBAAAAAAAAAAAAAAAAAAAAsP/aAAgBAwEBPwF4H//EABQRAQAAAAAAAAAAAAAAAAAAALD/2gAIAQIBAT8BeB//xAA1EAABAwIEBAQEBgIDAQAAAAABAAIRAxIQISJRMUFggQQTULEgQFKSMDJCYXGhYnIUI7DA/9oACAEBAAY/Av8AxW9bw1aHg9dufsEXvKD2GCFByeOI66ezcIseIIwFRnEK9vcddeYz84/tQcLm8OYWh2e3XXn0m5/qGIewwQgyrodv10anh/tVrxBx8urqburqbp652furXjvjcw9llk7brmyo2QjUp6mY3sMEKyqYf79dF9DJ2yhwg4to1/u66zEO5FWvb3xsqmWeyvYZB65LHhbs3xyzbsrmO7dc2vEhGpSEs9sbqboQDzbU66NXw/Hm1QRBxtq62qabu3XN7NL/AHUVGxjLHEFBniPuVzDI64tqNkIu8PmPpUOEHHQ7LZWu0O/frmHNg7hS0Xs3+ANfqYppu7ep2MzeVN62eOI6EupaHK17e+MscQUKdf7lI9QLWmamyL3mScHHlHQtr2yFd4fMbKHCDjB1M2Qew+neVRzdzKucZJwDGCSVH6jx6HhzYO4RBEt5HG6m6FY/S/39MdRofdiGMEkqTm88T0TDhIXmeHGXNqg4SEGVtTd1fTdI9IueYCdTo5z+rEMYEABq5noyRpfuix4xmmf5Chxsft6MXvKJJ08hiGNH8qKY/k9HWvaCi6jqbt8Hl18xyKljgR6FL3ABEUhcd1dUPbHJsDcq1vHmekS+npf7qKjYxljuyBBh3MegFrNT1NR3b4PNrjPk3pS2o2VcwXMxlpgry6mVQf387rfnsi1uhvwaKZXmVdTtulzUoiH+6teIOFzTBCFKtk7ff5q55gKzw+X7qXGTjFNvdBz9T1kI6ZkZPHAq2o2MbautquY7t8vrOrZZ5N2xhjSSr/EfarWNgdOWu48irXcORxuY6CrfEZHdS0yPk5JgK2hqO6L3mScbn6WKKbe/T9tRshF9DMfSocIOP1M2Usd2+R43O2CMmG7Y2MEkoP8AEZnbqPUIO4RdFzN8Q9hghBlTS/3/ABrqjoRbR0t3UnEQIbuss3b9S2uEgov8P9qhwg4hlfNu6vYZB/CkmAiyhmfqU1HE42saSrq+o7KAIHVH0v3UVB/Bx0mW7K5vHmPwJqO7KxulmMBB1bS3ZW02x1XZUbIV7NTPbG6m6EGuMVNviLKJl/srnuk45C1u5WTZdueroIkIvoZHZWuEEYXNMELyq2TuRxveYAVlEwz3xhokq/xGX7K1ogDrEloipuix4gjEM8RmN15vmC1QMmDgMYY3ushLuZ60II1cioqD+DjE4ipVEM91DGgDrYitnsFlw+Aec6GoRw61kmArPD5n6lc90n4hTqamIPYZB6zmo7srG6WYw0SUKviBn9Ki20jgQrXcORxBB08wpY7t1iWU9T/ZF7zJOPC1u60iTucbajZV1KXM9sQ9hghBlTS/36uko0qHDm7G1oklX+Iy/ZWtEAfEanh/tUOEHGyvqG6uY4Hqu6o6FDSWs2xDGBXHU/8AB+l+6LHjG6m6EG1tLt+qbfzP2Re8455MHEq2m3v+HFRsovpa27KDiKdTUxX03SOpvKoZu5lXOMk4+b4gZcmqGiB+NMWv3C1jTvjcw9llk7bqO95gBWUTDPfEMYJJQqVNT/kSx4kFX0NQ2xuYYKFOsYf79Ql7ys8m7Y2gaeZWgZ7/AChqUtL0WPEEYinWzbvsr2GQenrnu7K53DkMRUqiGe6hjQB8sQRq5FRUH8HHLNuyEGHbdOXE6uQRe84itWGXIfM2VAr26mYyDBWbr2/urmHt0zlm88Ai95knEVfEDPkPm4IkIvoZH6VbUbBxvpugqDk8cR0v5dMzUP8ASlxk4WtEkoVKol/t89FRsovoun/FQcL2GCF5dTKp79KSTAXleHOXNyk4BjBJKD3aqnoN9OGv90WPEEYXNMEIU6ph/v0lc93ZHVDNsQxgW79/Q5GTxwKLHiCMfKrnPk5SOj7WG56uqOnEFwinurabY9FII1ciix4xsqS5nsppunoy55gLyqGTeZxgCShV8QMvpUAQPR7XceRWsZb43U3QrH5PHRWs6tlnk3bG2m3upIufv6UWPEgq6hqbsoIg4B7DBCg5PHEdEeXS1O3Re8yTjc/SxWUx6aS0RU3RY8QRgHsMEIMdpqdDGjROfM42MEkoP8RmdvUJGTxwKLHiCMLmmCEKVXJ++/Qho0TnzONreHMrLN2/qUjJ44FFjxBGIpeIOfI9A3vMAKyiYZ742sb3QY0fz6paRq5FFjxj5Vc6eRVzTIPr1zz2WeTdsbQNPMoMYPVrXt7q13DkcbHamK+mfXIGbzwCuqOnEPqaWe6DGCAPWLajZRc0TT3xupu7LPJ44j1q93YI1Hc8ICFWvx5N9btcJBXm0M28xjLTBQpeI7OUj1i0HQ3hha0SSg5zZqHf165gteix4gjHy6hmmf6VzTIPq3k0zqPHH/kPH+vQBa9vdZiW8jjY7UxXMd29Uc4mICc4mZOAZy5oMbwHQMOEheZTzpn+sbmOgoU6+X+Xqdo/UcQ/9T+g7XCQUalDMfSocIOPlVzp5FXNMg+otHKMGUxzKDRy6F1CDuFu08Djb+ZmyFRnqDf9cGdDljwrvzM3x3YeIX/W+f29Pa+MowaQOHHoi1wkFebQGnmMQ9hghBsw/b06yoFlVyVrB36K82gMubVBwuaYITHnj11fSEVPdRUaQgxgklNp7dd62By0MA/+En//xAAqEAEAAQMEAQMEAwADAAAAAAABEQAxQRAhUWBhUIGRQHGhsSAw0bDAwf/aAAgBAQABPyH/AIVs2fvDTMLnD3s2eangsuxxSk0Yo+h7o70pjDFTTEZ0b6gftNuB70duOiMEJoGSX7tC0+bv3qV8YfvVKNJP9ANCCRke8ICEkaW9ndq/SWHUsaFsijBD4x3mSWrVtdNhZ1tdN1ZqC7e77yvFUmEWMmppdslFhnl7yQEJI0W2fi06aGHQVSMJX4iVEEjI95fww7NN1BO2DqWW+WhodsneZ4w2eKkt62uC7+7ouJY3yO8vgthrIK01GGPxmga5Bz3lAQkjTBOX+FJ3BcdBVIwlKbn5yoxFyrnebeDSTfzw6kiLho0KPCjwWyd4gZ81Pl5GKdNDDqLX5u1fADY0IkneEIsN6mCOBqKMlLrj5uVGIuVc9TMgPwqHJMm0U7Y6GRAQkjQmx+NpYsj2OpIi4ai+E7FJECcnqBxMXCko6KLhy9FZGbmpfzjp00MOpRnnURNm5k9OBFLHBSRFwuiUaUps776OhFhvUyHAmoRiqwB+llglr8QaKqVldEo0j4HsjpLoqYabfXExUCEeHSRCPJW+D5xQ8XpE+CWWmFqEUWWXSeMt3ijpvvemNCONTEyLOHXaVH7DRAHI9GjjBY5p6Z7XVfkLu4K2lV+49OZjXmk/28UioSE0FUjCUKK/G0SYuH0JkRctTjnlarABYWNTktYGCX7vUfMGeKSb+eHWW6M4NEhyL9eoEtDrj4sVOImBY1BUBK0Jnq5igBAQHU3BD5xTNzu0XKRGHQ00MlHnPrQaIcBehN24LtKrLoCsFRb7xIos4FsDqyCQ0AG+hR+ksOgRFglJWnB9VPgllpp2Vl06amXWcRMqxQ44+bFCwH2HWX4HuinDH5zoKpGEpTc/OUMGz7j6e8HA3qC7ex1JMXBUMseFEjFx1yJsH2aibL93Uk4uKh/GGjRUyfRpzBdalTPjlJR1SADzt2oxByrvX4GfNUx8/KpfQw652l21DdOcj6GGNCOlex1NLtgraCNw2oAQEB2L7O2r2wDVSaMV4gxx/cSEFJ/t5qRCvLq9K93Uw3932VIC4GnCp8qdNDDoKpGEr/3nSjQ7ZP6k5gutRHx8Kl1fOpNa8VCufHKDmCwdoxsLEraVH7Drm47upmwfZ/ojEHAu1K3G2XWBCvBSf7eaCEHa14qr+LqMMfjNHEzcv4qBLRtbc4oyc3Os6oYHBn7dJzJca248nzpIi4HQIiwSgBSxyauh3y1NyeSiqy6Gmpgpo2Vw0EBYB3EiBbgzSUdEKpGEraCNg3q6SNt6fo+6NZbozgUfhh3e6HTPe1tKj9h1zCOJ1yCsKEiLg7sdQ2xeamcYw/gAxz8tABi2juqcwXWnXaLq1MnNzqouJqGEWclBR7moxBwLtStxtl1l9TBXlQH+q2jCjAqJsv3dXpvtahunOR3HxBniik0Z1FpyXX3dus4IfOKj0n51KTRivEGOO3JEActTP4f4UqpWV0CIsApo2Vw0EBYB/FAQkjS3s7tXTQw6CqRhKLAceRRMa8drSEFOQnYGdZ4y3eKXm8zj+nGwsSo4yWedQjFQf6eaEEjI9oBQ+PTE2bGDWVhrAABzk/1wb+eSg/2AVAhHh1DCLOSh4uyygS0DIfA0kRcLoCoCVoDBuTNQ+hg/umqgvBwNtbXTdWagu3u+xuh3y1NyeSiqy6JRpJhFjB9CFGkWo58ikVCQmh9JZKADbFoIknYI4wWOagu3sdRKj4NCiXN3+ke3Jcw0lHRCjJU+ePOhodsnXm4hjbJpMkH2dcgrChIi4Ppjpnva2lR+w6xDf3dHQvd9cUifk1PGWxxq65a+aAEBAfUKZg54oGV5+NQ7gslALxuUvdF1c6ygGe2KUmjOgKgJWiyFbrigBAQH1ScyXGpj5+FSM+bUeqo+h7o6uuFkFHTUy6BEWAVkFYfXIN/PJTnibyvUCEeHQ0u2ShqgdUJzBdaQwbAzUiFeXRKNIywN1x6DGkPxRKOiCIsErAKx6kbiGNsmhBWI6sTZu4Kkl6/od+B7opKOiFUjCUJji5mpECcnTlAlpmZzaLFOGPzjViBbqzQQg9FOme9qOMlnnWdKfmkG/jk6Y+CWWkZH5GlVl0DuSwV5UB/qg5gsHo6YIPs0rJcTbUwx+M0bAfldKvBwN6gu3sdQCHnAoULLw9KCjSQfuxSdwXHRKNI+h7o6Q2MC+BSUdUgA87doTEDPPppEC3Bmko6JKNIywNxz0Yxw08UqpWV0NLtgraCNw2oAQEB6e/A90UlHRBEWCUE3Dw6GUCWiEu7eKVUrK6RNg+zUw3936k/A90UpNGdBVIwlNgI2XNCCRkegOh3y1NyeSiqy6F1JO+BQ/JDdy+qKRHwajjJZ51iH6hoICwT16902F2oLt7HUSo+DUcYLvPqzcSxtkUmCX7usLcbZKEzBxx64/Q9kU4Y/ONfMGOaCTBj1hwQ+cU8TFw1AIOcGoWj1rC/ebcjTiyv40gQrwVE/l/pQAgID1pIC4GkYH4GkRh0l9DJUzNrf6VIgTk9XUErAUo3DGgIiwChVbhcPXUEhpmYzaLNKTRnUcrIaBAWCerMpuNg1cN3tLoAkpTbIp/LLs6gwvHxQwbPuPVIAhGakCEZ0LBt3fij8gYOguiphp8bqBJxcVGkTtQQSMj6k88TFrfYUr0NIC4GlWZeRUvoYdYh+oaCAsE9RdL2W6hAFiCOi/Z21HRdaIifPpiZG/jvKGeMNnikUHj6wR3VFol8vTyXTCdJCgZXSEgLgaiP6h1aYjFCWFdn05TMHPFblDK0Ve6bq70lAQkjSmerGKgQjw6BEWCVe7G/eorApLq+aUmjFTe7jfvZsfeCmZXeD/ok//9oADAMBAAIAAwAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACxCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAgCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAjCAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCBAQQAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxAQgAAAAAAAAAAAAAAAAAAABjhiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAQQAAAAAAAAAAAAAAAAABxBCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASyAAAAAAAAAAAAAAAAAwiRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBgCggAAAAAAAAAAAQhByiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARDQgAAAAAAAAAjgTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCRCQgAAAAATAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABjQgAABAACiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQwQwTyBzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCzBABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQyAgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwADAQDAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxBjAAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARwRwAAAABCwiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATiCCAAAAAAABSwSQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATgAAAAAAAAAAABCQCQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiBwgAAAAAAAAAAABBQiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByBQAAAAAAAAAAAAAAADCTSwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATQASAAAAAAAAAAAAAAAAABCQCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjgSAAAAAAAAAAAAAAAAAAAAAARggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzgQAAAAAAAAAAAAAAAAAAAAAAABBBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzASAAAAAAAAAAAAAAAAAAAAAAAAADQjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAiAAAAAAAAAAAAAAAAAAAAAAAAAAACQSQwAAAAAAAAAAAAAAAAAAAAAAAAAAACDiAAAAAAAAAAAAAAAAAAAAAAAAAAAAADARCwAAAAAAAAAAAAAAAAAAAAAAAAADBSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhiQgAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADABQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/8QAFBEBAAAAAAAAAAAAAAAAAAAAsP/aAAgBAwEBPxB4H//EABQRAQAAAAAAAAAAAAAAAAAAALD/2gAIAQIBAT8QeB//xAAsEAEAAgEDBAIABgMAAwAAAAABABEhEDFhQVFgcVCRQIGhwdHhIDDwsLHA/9oACAEBAAE/EP8AwrZIE4MURbtDN52LijVIclTPgdCpZh4Ww+4fBsr9jzqxoYeYjExQ350qoLddE7THI5W/nQ3pXx0B0j1Foj0dHgqpnAi8CLRQ85QSnJLRsrDioRGnDol5LEYQYpVnN+0MmBYnXzhyYFI9YRRZ0HupuxaGnQUbMMeX1E4e0YDS22eD5yfSbWN+GZ4M2uM8GKYspTLmfZx5yoAbXuPEv9i0GGIjTh0VyFomNt4lHrzBEsyecOTApHrKqvdH6PaKO2kK0MuRYnSbo5T9X/MMmBYnXzmrZoBSPPeBOCKvpdBRswzG28S314guQtHnIZwbGX3IeS7WNuHWylsuY9nMScA3faec7tWhsjN1sm/9IiNOHQgNbbY4Mqv6lULiCJZk84cmBSPWKFzo7MICGgUmhlyLE6QgmwLf1OsrLG4pPXnNswmUMcGKcmoR9DqqdLGqADNAfvE2atLZ5w6dug29QVu/1PSKO2kK1HgDaLUpFDNzJwwAgjsj5x0MQFCHcOQ8hyREacOgBETZGIoxE2HDKyxuKT18mcZrB2PdgIBWvg8RgDE6Xs8DcmBSPWMA3DR+h0gCpUA+h1VOljVL0WgcF8wwt5EsfkKBDoNuTEvJaroioNF0vwU9l0gjC8Fryeoo7aQrQUbMMNeN3yemBkDu5OyfGqBbghHsO7OJzHEFaLV0S8lAEAkxD37eD9DEBQgw+7oJqPP7l4fyhBSBhaORBEsyfFAiUBaxhwXbv2EcuRavXRLyUAQ+DZT6HhIjtpC4ivfcPIjgbwhSaGBvIlJH1hx1SUAN63Hn4jdq0tESmhrAeoiJatromdGxg92V0llMn+PC0EpyR142PD7ImQezg7jrbKos2I9w4XwvDBEsyfChnBuZfYl9JYXA/nVIwFJjrMplEWbnhwagqxk9Mu7AtX/THLkUj00MuRYnSOniC5fbiCnSxu+CFOlrVBUwowe0LUArTAK0ZZa2qU6KhwRWxleIIJTkgwh7oMkU5NQj6HU6M0vbD1Fh82RH8egQA3VgKMQNxyyssbig9amXIoDrBWnsuB3eYZMCgOnibAaUUzyIghDTY8xACJuJoo7bEqApChWg/wA/jXzSZVpiwba3ByxAiruroABV2AjZEN6Qhy+sjL3gAUYPFUACO4kMw7wR/absWhp0cQVopGVlUFOF/MESzJ+J3atLRCMpsLL6ijttS9ayxsKD3AUZi7jglEV2A8ZPg2E+jCA1opjkaGXIsTpCCbAt/U6xBULU/Yfh6NdF5KllLbcx7edVTpQXRUm+T95h7LoB446JtAy46ZtAwdX2XYqEDyUPD7gjtsS/wYAhtFBHKQUrc/eJeS1XQFaMssOLIUPEvLGwtPfj7p26Db1MEJubDjvG2FiNOr4XhY5IdWIXtJ6/AKBbgjsL4EtHmPDLLoDnvqrkKBHSFmzPcMmBQHTyK6GJQKSX5RcdM51sw8LYfcGUPVjkgiWZP9o8/sXl/KXdoUr/AKI4W8qWurwyw6A47xKNHBz+XbyUxBUCxIgN2r+0xR20hWhlyLE6RxDiDpee8FyFo/1ACG0UEwQm5seO8cNfdg/LVNQVYwe2OUgsG5+8AENAoPKDyHKxwy2VTRsamRks7D67Q0TeDl/6LyxuLT1HLh4Fw86mFvAFrLu0LB/0Qef3ay/n5WoAbXuPEtmUyhng6kBrbbHBlAh0m3I/xQIAbqy4s7DMH2XarUMzcQoTjvGcMYVq8doAFGDy0AQ0CxhxjC6Xx2jiCoFI6OIK0UjGPYNmcXmCJZk0FyFoijE+yn+kQIq7q6KO2gLjGU0ll9wxBUCgPMcaXGq3ZiXkpE0MuRYnSGkjNme4PeaLc8V3j8Gwv2dTqxS8oPcu2YAWrx280rpLCYP8S2VTRsaqhKdkqPy0BWjLGbjTN/6QU6UFXm2B1bj8rtEgiOC5D/CqdiXt0hlENQdKvNQBDaKCAqKrYPUfZdqtavOZLKvQUbMMv9ihOGBeSxHzO8sbi09Ry4eBcPOpbCwG2XFZW9qggq4aodM2gYOt9JZXI/mHViF7SevMFAtwQZQd0OSWYeNsHrVAg0hoTiXQ1KBa6sBpRTPIm/ejRfs4iI04dLMPC2H3BlD1Y5IIlmTy1wN5UoJUPgk3uHLkWr10cQVAtWMZTSWX3DEFQKA/xcmBSPWEUWdB7qKO2kK0MuRYnSHyNA7H7wNQXSyezysef2Ly/lMlokqndiq25dEzo2MHuw/iNVY9P9J5DlY4YmdGxg9zUef3Lw/lKu0aB/0QyYFidfKAtBsm3tiZB7uDsGoTdYlXwRsSFIfY/wCtTg1CPoYwaLdDF+8cDeEKTQUbMMv9ihOGKAG9bjz5KgQA3VlCjJvHrzHEFaLV0MuRQHWV2390MLYWA0f7UEpyQCuxgqt5JZrprJWueDFMWUplzPs48jFyFoijE+yn+kQIq7q6JeSgCV+xYjLAAowfgAvJSJD5G1dj945cikemmzFpaYZh1gj+0AII7I+QBnBuZfYllLbcx7edR9JtjAhteg7X4NBKckXwyv8AnzEvJSJoARE2RlYSaRsP3guQtHjwTgm76SPBVROBoCtGWM3Gmb/0gp0oKvw1dJYTB/iWyqaNjVKtnJx+XaHDLLpHjv44vpFE5UTOjcwexoCtGWOnDgPu8QyYFAdPxAKdt1LuS5IOaZ99UBDaKSHDJl7a4ZjgxeM4OLVA37Msw8bYPWhlyKA6zEkn6sYZMCgOn4oAQ0CxmSE3Nzx2jo26Df1qIAb1snMPg2V+x4soFuCDWSlLD/MUdtqXo4gqBasJutM2/tAAowfjVODUI+hmxcUbOI4G8IUmiuQtEFCeFwevPigAhtFBK7b+yCOFvKlrol5KAITYmAw+PgEEpyTqqFig5iXkpE0cQVopGE3Gmbf2giWZPEQnBN30kSUHPornvqmQezg7rH4TextwfBnwbCfRiXkpE0MuRYnSCtPTcDs8wwt5EsfDkCAG6sQQgtteYwGtlscDXGlxqp2IPP7tZfz+FrpLCYP8RM6NjB7mgo2YZ0VCzacQTg1ofsPDN2rS0SxRk2n14iBFXdXRAQ0C1lRWFve4AENAoPhzgisjKjpeg7WpAa22xwYcZrQ2Pc8Ko10XkqWUttzHt51LErSH2MZVcqXbsfFBeSkSWqblpICGgUmiXksRh8Gyv2PB1AtwQ5fUzl7RLyWq6ArRllhxZCh4gKd91Lu/G40uNVuzEvJSJol5LEYzYGQw+PBVAtwQ068h9TmOXItXrorkKBHSFmzPcMmBQHT48+DYT6MS8lImjiCtFIzAaqPH9kESzJ4EgQA3VhMhUr6nMcuRavXQ0zeBgxKNHBz+Xb5I+DYT6Mow8aYfWhlyLE6TEkn6MYZMCxOvgAuQtEUYn2U/0iBFXdXRJwBV9rAjAUmes/KD6RZGVEzo2MHuaCjZhliacNl4vEMQVosT57PBimLKW25j286j6TbGBAzg2Mvu/LJOCKvpY8FVkYGrlx8m4eICnfdS7Pzh8Gwv2YwGtlscDQFaMsWEvVhglGHhTL7+YYDSimeRLBDsN+DqWJG0fsIE3WLV8nzWeRwt4LZUaXZ2NDC3gC1lw+QzaoMmBQHT5oxBUCxJYoy7z68RACJuJoWysFpiyq8ne4MLeRLH5dyYFq9JeacJsvV0cQVAtWAxQEu/YgAUYPnEACO4kQQhppeZRh40w+tBRswxayUJa/4hiCtFifLH7HW9/dFVty6AEo0D7fAGw0AmTvcu2aAWJz21uSDi2fWIKhan7D5Q11kOmI66yHXOj6rOBBQzA48BEdtIXEUhaBa/41fZdiomCxHBfMMmBYnX5IGURF5rjWgQFxuh4GYgqBYkySps+g7xthYjToKNmGWJpw2Xi8QxBWixPkUA2ydA6BjaF+jeDEAwHHgt0MSgUk356E/R1S0G6bemUYXh1XZ+Q/SP20/9/wAHDODYy+5EtBsG3s1EO+muSActWPp8e5ljuWiuluwPCDEFQLEliacll5nERGnDoDEza34hTx19d1r44FO26l3IpJ2SyqZ4M3hOHJgUj1irX2XK7nEcDeEKTRxBWikYY+1XdOvnKCU5I1JuwUf2jgr7MP5yjDwpg9xrI+/6+dkgRkzRFu0c3/wk/wD/2Q==");
      this._noticeCtrl.notice("Kamera geht leider nicht im Browser, dafür musst du dir die APP installieren");
    } else {
      let cameraOptions: CameraOptions = {
        destinationType: this.camera.DestinationType.DATA_URL,
        encodingType: this.camera.EncodingType.JPEG,
        quality: 70,
        targetWidth: 1000,
        targetHeight: 1000
      };
      this.camera.getPicture(cameraOptions)
          .then((imageData) => {
            //
            this.base64Image.push(imageData);
          })
          .catch(err => this._noticeCtrl.notice(err));
    }
  }

  delete(gift: Gift) {

    let options = {
      title: 'Geschenk löschen',
      message: 'Möchtest du "' + gift.title + '" löschen?',
      buttons: [
        {
          text: 'Abbrechen',
          role: 'cancel',
          handler: () => {
            console.log('Cancel clicked');
          }
        },
        {
          text: 'Löschen',
          handler: () => {
            this._giftStore.delete(gift)
                .then(() => this._noticeCtrl.notice("Geschenk gelöscht"));
            this._nav.pop();
          }
        }
      ]
    };
    this._alertCtrl.create(options).present();
  }

  save(gift: Gift) {
    if (gift.title.length == 0) {
      this._noticeCtrl.notice("Titel darf nicht leer bleiben");
    } else {
      this._nav.pop()
          .then(() => this._giftStore
                          .addOrUpdate(gift)
                          .then(() => this._noticeCtrl.notice("Geschenk gespeichert"))
          )
    }
  }

  showDescription() {
    if (this.gift.description) {
      let opts = {
        title: 'Beschreibung entfernen',
        message: 'Möchtest du die Beschreibung entfernen?',
        buttons: [
          {
            text: 'Abbrechen',
            role: 'cancel',
            handler: () => {
              console.log('Cancel clicked');
            }
          },
          {
            text: 'Entfernen',
            handler: () => {
              this.gift.description = '';
            }
          }
        ]
      };
      this._alertCtrl.create(opts).present();
    } else {
      this.gift.description = "deine Beschreibung";
    }
  }

  showEstimatedPrice() {
    if (this.gift.estimatedPrice) {
      let opts = {
        title: 'Preis entfernen',
        message: 'Möchtest du den Preis entfernen?',
        buttons: [
          {
            text: 'Abbrechen',
            role: 'cancel',
            handler: () => {
              console.log('Cancel clicked');
            }
          },
          {
            text: 'Entfernen',
            handler: () => {
              this.gift.estimatedPrice = 0;
            }
          }
        ]
      };
      this._alertCtrl.create(opts).present();
    } else {
      this.gift.estimatedPrice = 10;
    }
  }

  share(gift: Gift) {
    this._noticeCtrl.notice("like to share (NOT IMPLEMENTED YET)");
  }

  asImage(imageData: string) {
    return "data:image/jpeg;base64," + imageData;
  }
}

